### ISSUE TITLE
ClusterInformation: connection is unauthorized: Unauthorized

### ISSUE THREAD

**Issue by ghost** [flexkube/calico-helm-chart#4]
Hello, I am getting this error
```
network: error getting ClusterInformation: connection is unauthorized: Unauthorized
```

And there seems to be NO `'calico-node'` `ClusterRoleBinding` and `ClusterRole` created with this chart. Is this correct? Is this the reason for the above error?

How I would go about further debugging?
What other info should I provide?

Thank you!

**Comment by invidian** [comment]
Hey @anatolbran, thanks for reporting the issue.

Where do you see the mentioned error? In `calico-node` pods? In events for pod creation?

I'm not able to re-produce this issue on my cluster. What K8s distro are you using? What version of Kubernetes? Are you using Typha?

The manifests in this chart should look very similar to upstream Calico manifests + templated parts which can be modified via values.yaml. Did you try setting up with upstream manifests? Do you get the same issue?

**Comment by ghost** [comment]
Hello @invidian 

I got the error when installed this chart with an Ansible playbook
After creating a different cluster and installing it manually with helm, everything worked.

I can still debug on the failed cluster if you want any details, but I assume it's because of a misconfigured/failed Ansible playbook

I can close/delete the issue at your request.
Thank you and sorry for the wasted time
Have a nice day!

**Comment by invidian** [comment]
No worries! I'll close it then. I'm glad you got it working :tada:
